name: Review
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
    review:
        name: ReviewSource
        runs-on: 'ubuntu-latest'
        steps:
            - name: Code Review
              uses: packocz/sfdx-code-review-action@v0.3.0
              with:
                  source_path: '"***.cls"'
                  reject_threshold: 1
                  max_comments: 20
                  category: '!Documentation'
                  engine: 'pmd, eslint'
                  dfa_setting: 'dfa'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
