name: Pull Request Stats

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          repositories: 'rayraja1992/TestRepo2'
          period: 7
          charts: true
          disableLinks: true
          sortBy: 'COMMENTS'
